### ISSUE TITLE
Comscore prevents analytics.ready() until after .page() is called

### ISSUE THREAD

**Issue by elgreg** [segment-integrations/analytics.js-integration-comscore#6]
I found that if include comScore in my initialize, my analytics._readied is false _until_ I call analytics.page()

In debugging, it looks like the `initialize` method isn't actually called until page() is called. Is this expected behavior?

My use case is that I want to wait for my integrations to be loaded before a component on my page starts firing events (specifically, I need to use something _inside_ of Amplitude's object and I need to know it's going to be there.

The `.ready()` method seems like the place to hook in to know that the `amplitude` global is on the page, but Comscore is preventing it. At this point, I may end up firing a .page() to comscore only so that I can get the ready event firing for everything else, but this seems like a hack.

 I'm using v2.11.0 of https://github.com/segmentio/analytics.js and saw that issue [#409](https://github.com/segmentio/analytics.js/issues/409) would probably solve my issue.

To repeat:

Ready will _not_ ever fire in this setup:

```
analytics.initialize(        "comScore": {
          "c1": "2",
          "c2": ""
        });
analytics.ready(function(){ console.log("ready") });
```

But if I call page inbetween, I _do_ get a `.ready()` call

```
analytics.initialize(        "comScore": {
          "c1": "2",
          "c2": ""
        });
analytics.page();
analytics.ready(function(){ console.log("ready") });
```

**Comment by f2prateek** [comment]
Yes, this is expected for certain integrations.

Some integrations require a `page` call to be initialized because they initialize on page loads rather than via init methods. The comScore integration is one such example https://github.com/segment-integrations/analytics.js-integration-comscore/blob/master/lib/index.js#L15.

But ready only fires when ALL integrations have initialized. Hence if you don't call page (without which comScore won't initialize), all integrations have not initialized and hence the ready callback isn't invoked.

**Comment by elgreg** [comment]
OK. That makes sense. for the time being I'm now doing:

```

  const logComscore = (el) => {

    analytics.page('pageView', {}, {
      integrations: {
        'All': false,
        'comScore': true
      }
    });
  }
```

and then a separate function that uses a ready and doesn't fire comscore.

Is there an attribute of integrations that would indicate that this is their behavior?

**Comment by f2prateek** [comment]
Hmmm... In not aware of any. One way might be to check for the string assumesPageView in this org and see the results.

@Peripheral1994 might know though

**Comment by Peripheral1994** [comment]
I don't believe there's a comprehensive way to identify this without going to the repository and checking for an assumesPageview(). This should be something that we put in our documentation per-integration. I'll make a ticket on our end to make sure that we find a better customer solution for this.

**Comment by elgreg** [comment]
Thanks! Firing the [individual ready-events](https://github.com/segmentio/analytics.js/issues/409) would resolve my specific use case, but documentation would be a great first step for any of these that operate differently. I'm guessing most people just fire the pageview right after loading analytics.js and never notice that ready is tied to these.
